name: Build in Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine
    steps:
      - name: Test Docker
        run: lsb_release -a
