name: Build in Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian
    steps:
      - name: Test Docker
        run: |
          cat /etc/os-release
          apt update
          apt install -y qtbase5-dev
          qmake --version
